// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9n4cntilckaTkhfHhHsCGmBx4USQgBNo',
    appId: '1:514349821431:web:dd4e8cfcf5e2cd12e012f2',
    messagingSenderId: '514349821431',
    projectId: 'imperial-community',
    authDomain: 'imperial-community.firebaseapp.com',
    storageBucket: 'imperial-community.appspot.com',
    measurementId: 'G-FCHFVCQ8EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN8HJRp0UbHwUEenOaFjDRNVKEKSMvY-0',
    appId: '1:514349821431:android:ef19eeaba754d3c6e012f2',
    messagingSenderId: '514349821431',
    projectId: 'imperial-community',
    storageBucket: 'imperial-community.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsbchcPDcWMF_Zfy3bwXtrki38U3vKdfE',
    appId: '1:514349821431:ios:da24ef93c70ec501e012f2',
    messagingSenderId: '514349821431',
    projectId: 'imperial-community',
    storageBucket: 'imperial-community.appspot.com',
    iosBundleId: 'com.example.imperial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsbchcPDcWMF_Zfy3bwXtrki38U3vKdfE',
    appId: '1:514349821431:ios:da24ef93c70ec501e012f2',
    messagingSenderId: '514349821431',
    projectId: 'imperial-community',
    storageBucket: 'imperial-community.appspot.com',
    iosBundleId: 'com.example.imperial',
  );
}
